[platformio]
src_dir = build_targets
default_envs = access_point, node_1, node_2

[env]
platform = espressif32@7.0.1
board = esp32dev
framework = arduino
monitor_speed = 115200

[env:access_point]
build_src_filter = +<access_point.cpp>

[env:node_1]
build_src_filter = +<node_1.cpp>

[env:node_2]
build_src_filter = +<node_2.cpp>
